sonar.organization=nikscool24
sonar.projectKey=docker-2tier-project-group-2-clone-key




# # --- Metadata ---
# sonar.projectName=docker-2tier-project-group-2-clone
# sonar.sources=.
# sonar.sourceEncoding=UTF-8


# ---- Exclusions ----
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts, **/coverage/**