sonar.projectKey=docker-2tier-project-group-2-clone-key
sonar.host.url=http://host.docker.internal:9000



# --- Metadata ---
sonar.projectName=docker-2tier-project-group-2-clone
sonar.sources=.
sonar.sourceEncoding=UTF-8


# --- Exclusions ---
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts, **/coverage/**