---
name: DevSecOps

on:
  workflow_dispatch:  
  push:
    branches: [dev]

permissions:
  contents: read
  packages: read
  security-events: write    

jobs:
  Code-Quality: 
    uses: ./.github/workflows/CodeQuality.yaml
    secrets: inherit   
 
  
  GitLeaks-Scanner:
    needs: Code-Quality
    uses: ./.github/workflows/GitLeaks.yaml
    secrets: inherit

  CodeQL-Scan:
    needs: GitLeaks-Scanner
    uses: ./.github/workflows/CodeQL.yaml
    secrets: inherit

  SonarQube:
    needs: CodeQL-Scan
    uses: ./.github/workflows/Sonarqube.yaml
    secrets: inherit

  Snyk-Scanner:
    needs: SonarQube
    uses: ./.github/workflows/Snyk.yaml
    secrets: inherit
    
  Docker-Scan:
    needs: Snyk-Scanner
    uses: ./.github/workflows/DockerScan.yaml
    secrets: inherit