---
name: DevSecOps

on:
  workflow_dispatch:  
  push:
    branches: [dev]

permissions:
  contents: read
  packages: read
  security-events: write    

jobs:
  Code-Quality: 
    uses: ./.github/workflows/code-quality.yaml
    secrets: inherit   